### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by andreasevers** [in-the-keyhole/khs-trouble-maker#2]
Hi,

I'm trying to integrate Kubernetes support into Troublemaker, but I noticed you're not using spring-cloud for service discovery. Is this a conscious decision to avoid dependencies to spring-cloud or due to technical limitations?

You could use the `@EnableDiscoveryClient` annotation on your `Application` class, which would autowire a discoveryClient, useful for easily querying Eureka as you do now. You'd also get integration with Consul and Zookeeper out of the box.

If you would use spring-cloud's abstraction, I'd be able to easily plug in Kubernetes support as well (through https://github.com/fabric8io/spring-cloud-kubernetes).

Cheers,
Andreas

**Comment by jaimeniswonger** [comment]
Andreas,

We have an open branch of this where we are bootifying it, and will be switching to the pure Spring Cloud discovery abstraction...we will get this updated quickly (hopefully today), and let you know.

Thanks!

**Comment by jaimeniswonger** [comment]
This issue should be taken care of...now using @EnableDiscoveryClient directly, and full spring boot/cloud configuration.  Let us know if you have any issues.

**Comment by dpitt** [comment]
Andreas, 

     No sure if you where notified, but we bootified the project, to utilize Spring Discovery.  Issue has been closed, but if you run into any problems, let us know and we will resolve. 

Thanks, 
David

**Comment by andreasevers** [comment]
Awesome! Got the notification this morning (I'm in Europe), delightful news :)
I actually started a Spring Boot migration on my separate fork, but I'll rebase and see if I can add some value to what you guys have done.
