### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by ryanjbaxter** [in-the-keyhole/khs-trouble-maker#6]
There is a bug in the README.
`java -jar khs-trouble-maker.jar -Deureka.serviceUrl.default=http://localhost:8761/eureka/`

should be

`java -jar khs-trouble-maker.jar -Deureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/`

**Comment by jaimeniswonger** [comment]
Fixed. Thanks!
